version: '3.4'

services:
  d4prototypelearningplatform:
    image: d4prototypelearningplatform
    build:
      context: .
      dockerfile: D4PrototypeLearningPlatform/Dockerfile
    depends_on:
      - db
    ports:
      - "6543:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  # you can run a test db with "docker run -it --rm --name pg-docker-d4db -e POSTGRES_PASSWORD=SuperSecurePassword4267 -p 5432:5432 postgres"
  db:
    image: postgres
    container_name: d4db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=SuperSecurePassword4267